import { writeFile } from "node:fs/promises";
import path from "node:path";

import {
  activeJourneyDefinitions,
  deferredJourneyDefinitions,
  holdLockedJourneyDefinitions,
  type JourneyDefinition,
  type JourneyStepDefinition,
} from "@/lib/journeys/journey-registry";
import type { ScreencastDefinitionFile, ScreencastJourney, ScreencastStep } from "@/scripts/screencast/lib/types";

const outputPath = path.join(process.cwd(), "docs", "v3", "journeys.screencast.new-system.json");

const tenantByJourney: Record<string, { name: string; slug: string }> = {
  "MJ-001": { name: "Morgan Family Office", slug: "morgan" },
  "MJ-002": { name: "Morgan Family Office", slug: "morgan" },
  "MJ-003": { name: "Northbridge Family Office", slug: "northbridge" },
  "MJ-005": { name: "Summit Ridge Capital", slug: "summit" },
  "MJ-006": { name: "Bennett Family Office", slug: "bennett" },
  "MJ-010": { name: "Northbridge Family Office", slug: "northbridge" },
  "MJ-012": { name: "Morgan Family Office", slug: "morgan" },
};

function titleCaseRole(roleKey: string) {
  return roleKey
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function stepCaption(definition: JourneyDefinition, step: JourneyStepDefinition) {
  if (step.clientVisible) {
    return `${definition.journeyKey} shows a client-visible outcome only after the gated journey state allows it.`;
  }

  if (step.requiresAudit && step.requiresEvidence) {
    return `${definition.journeyKey} keeps evidence and audit requirements visible before the journey can move forward.`;
  }

  if (step.requiresAudit) {
    return `${definition.journeyKey} requires an audited human action before this step can advance.`;
  }

  if (step.requiresEvidence) {
    return `${definition.journeyKey} separates linked evidence from final acceptance or release.`;
  }

  return `${definition.journeyKey} is shown from the Wave 0-2 journey spine, not from the retired Jxx typed workflow path.`;
}

function screencastStep(definition: JourneyDefinition, step: JourneyStepDefinition, index: number): ScreencastStep {
  return {
    step: index + 1,
    id: `${definition.journeyKey}-S${String(index + 1).padStart(2, "0")}`,
    title: `${definition.journeyKey}: ${step.title}`,
    role: titleCaseRole(step.actorRoleKey),
    roleKey: step.actorRoleKey,
    tenant: tenantByJourney[definition.journeyKey]?.name ?? "Demo tenant",
    tenantSlug: tenantByJourney[definition.journeyKey]?.slug ?? "northbridge",
    route: "/journeys",
    screen: "Work Dashboard",
    inputData: [definition.journeyKey, definition.title, step.stageKey, step.key],
    action: "Inspect journey worklist state generated by the new Journey Spine",
    target: null,
    interaction: { type: "none" },
    navigation: "goto",
    dataRefs: [
      "lib/journeys/journey-registry.ts",
      "lib/journeys/journey-state-machine.ts",
      "app/api/journeys/route.ts",
      "app/api/journeys/[id]/commands/route.ts",
    ],
    caption: stepCaption(definition, step),
    expectedVisibleText: ["Work Dashboard", definition.journeyKey, definition.title, "Next safe action"],
    expectedStateChange: "The screencast reflects the seeded Journey Spine projection without calling retired Jxx actions.",
    blockedActions: ["Retired Jxx typed workflow compatibility path", "Advisor approval as client release"],
    clientVisibility: step.clientVisible ? "Client-visible only after release gate" : "Internal or gated until release conditions pass",
    evidence: step.requiresEvidence ? "Evidence requirement remains visible in the Journey Spine" : "No evidence sufficiency claim is made by the screencast",
    audit: step.requiresAudit ? "Audit is required before command acceptance" : "No audit completion is claimed by the screencast step",
    qaAssertion: "Dashboard renders from the Journey APIs and does not depend on retired legacy screencast actions.",
    pauseMs: 1200,
    screenshotName: `${definition.journeyKey.toLowerCase()}-${step.key.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}`,
    manualOrStatic: false,
    sourceProof: [
      "ALPHAVEST_TRUE_UX_IMPLEMENTATION_HANDOFF.md",
      "lib/journeys/journey-registry.ts",
      "tests/journey-spine.spec.ts",
      "tests/journey-api.spec.ts",
      "tests/journey-ui.spec.ts",
    ],
  };
}

function journeyForDefinition(definition: JourneyDefinition): ScreencastJourney {
  const tenant = tenantByJourney[definition.journeyKey] ?? { name: "Demo tenant", slug: "northbridge" };
  const primaryRoleKey = definition.actorRoleKeys[0] ?? "client_success";

  return {
    id: definition.journeyKey,
    name: definition.title,
    portfolioLayer: "P0",
    candidateId: definition.journeyKey,
    demoPriority: "P0",
    audienceFit: ["customer", "executive", "compliance"],
    currentRealityLabel: "new-system-journey-spine",
    proofLevel: "PL4",
    overclaimRisk: "A screencast can show journey state and safe next actions, but it is not production authorization.",
    caveat: "New-system screencasts must not call retired Jxx typed workflow actions or claim client release from command acceptance.",
    proofPath: [
      "lib/journeys/journey-registry.ts",
      "app/api/journeys/route.ts",
      "app/api/journeys/[id]/commands/route.ts",
      "tests/journey-spine.spec.ts",
      "tests/journey-api.spec.ts",
      "tests/journey-ui.spec.ts",
    ],
    captionShort: `${definition.journeyKey} runs from the Wave 0-2 Journey Spine.`,
    captionLong: definition.description,
    presenterNotes: [
      "Use this as current-system demonstration only.",
      "Do not describe retired Jxx actions as current implementation truth.",
      "Show gates, blockers and client visibility boundaries explicitly.",
    ],
    customerSendable: true,
    primaryActor: titleCaseRole(primaryRoleKey),
    additionalRoles: definition.actorRoleKeys.slice(1).map(titleCaseRole),
    tenant: tenant.name,
    startRoute: "/journeys",
    endState: "Journey state, next safe action and client-visibility boundary are visible from the new Journey Spine.",
    demoSession: {
      mode: "demo",
      defaultRoleKey: primaryRoleKey,
      defaultTenantSlug: tenant.slug,
    },
    queryParams: {},
    preconditions: [
      "Demo auth session is active",
      "pnpm db:seed has created Wave 0-2 Journey Spine data",
      "No retired Jxx screencast action is required",
    ],
    demoData: [definition.journeyKey, ...definition.foundationIds],
    visibilityRules: [
      "Command acceptance does not equal client release",
      "Client projection remains governed by the Journey APIs and release gates",
    ],
    complianceRules: [
      "Human review, audit and evidence requirements remain explicit",
      "Advisor approval alone is not enough for client visibility",
    ],
    evidenceExpectations: definition.evidenceRequirements.map((requirement) => requirement.title),
    auditExpectations: definition.steps.filter((step) => step.requiresAudit).map((step) => step.title),
    riskNotes: [
      "The screencast is a current-system walkthrough, not a production authorization proof.",
      "Generated videos must be recaptured after Journey Spine behavior changes.",
    ],
    steps: definition.steps.map((step, index) => screencastStep(definition, step, index)),
  };
}

function holdLockJourney(): ScreencastJourney {
  const holdKeys = holdLockedJourneyDefinitions.map((definition) => definition.journeyKey);
  const deferredKeys = deferredJourneyDefinitions.map((definition) => definition.journeyKey);

  return {
    id: "MJ-HOLD-LOCKS",
    name: "Hold Locked And Deferred Journey Boundaries",
    portfolioLayer: "P0",
    candidateId: "MJ-HOLD-LOCKS",
    demoPriority: "P0",
    audienceFit: ["compliance", "executive"],
    currentRealityLabel: "new-system-source-lock-boundaries",
    proofLevel: "PL4",
    overclaimRisk: "Viewer may assume all known journeys are executable.",
    caveat: "Only active Wave 0-2 journeys are executable; hold-locked and deferred journeys are displayed as boundaries.",
    proofPath: ["lib/journeys/journey-registry.ts", "lib/source-lock/wave0-2-source-lock.ts", "tests/journey-spine.spec.ts"],
    captionShort: "Hold and deferred journeys stay visible without being executed.",
    captionLong: "The Journey Spine shows what is active, hold-locked and deferred so the demo does not silently overclaim scope.",
    presenterNotes: ["Use this to explain scope discipline before showing active journeys."],
    customerSendable: true,
    primaryActor: "Compliance Officer",
    additionalRoles: ["Executive"],
    tenant: "Northbridge Family Office",
    startRoute: "/journeys",
    endState: "Hold-locked and deferred journeys remain visible as blocked boundaries.",
    demoSession: {
      mode: "demo",
      defaultRoleKey: "compliance_officer",
      defaultTenantSlug: "northbridge",
    },
    queryParams: {},
    preconditions: ["Demo auth session is active", "Wave 0-2 source lock is loaded"],
    demoData: [...holdKeys, ...deferredKeys],
    visibilityRules: ["Blocked journeys are not executable", "Deferred journeys are not promoted by screencast demand"],
    complianceRules: ["Scope locks remain explicit"],
    evidenceExpectations: ["Hold lock is visible in the Journey Spine"],
    auditExpectations: ["No mutation is claimed for hold-locked journeys"],
    riskNotes: ["Do not present hold-locked journeys as current implementation."],
    steps: [
      {
        step: 1,
        id: "MJ-HOLD-LOCKS-S01",
        title: "Inspect hold-locked and deferred boundaries",
        role: "Compliance Officer",
        roleKey: "compliance_officer",
        tenant: "Northbridge Family Office",
        tenantSlug: "northbridge",
        route: "/journeys",
        screen: "Work Dashboard",
        inputData: [...holdKeys, ...deferredKeys],
        action: "Inspect visible journey boundaries",
        target: null,
        interaction: { type: "none" },
        navigation: "goto",
        dataRefs: ["lib/source-lock/wave0-2-source-lock.ts", "lib/journeys/journey-registry.ts"],
        caption: "The dashboard keeps blocked and deferred journeys visible without turning them into demo claims.",
        expectedVisibleText: ["Work Dashboard", "MJ-004", "MJ-007", "HOLD_LOCKED"],
        expectedStateChange: "No journey mutation occurs; the screencast proves scope boundaries only.",
        blockedActions: ["Executing hold-locked journeys", "Promoting deferred journeys"],
        clientVisibility: "No client visibility change",
        evidence: "Source lock boundary only",
        audit: "No audit completion claimed",
        qaAssertion: "Hold panel renders source-locked journeys without executable controls.",
        pauseMs: 1200,
        screenshotName: "mj-hold-locks",
        manualOrStatic: false,
        sourceProof: ["tests/journey-spine.spec.ts", "tests/journey-ui.spec.ts"],
      },
    ],
  };
}

async function main() {
  const manifest: ScreencastDefinitionFile = {
    schemaVersion: "4.0.0",
    engineMode: "ENGINE_MIX_V2_CODEX_V3_PROOF",
    outputRoot: "artifacts/screencasts",
    sourcePlaybook: "lib/journeys/journey-registry.ts",
    generatedFor: "AlphaVest WealthOS new-system Journey Spine screencast automation",
    manifestId: "journeys.screencast.new-system",
    portfolioLayer: "P0",
    requiresPortfolioMetadata: true,
    speedProfiles: ["human-demo", "qa-fast"],
    journeys: [...activeJourneyDefinitions.map(journeyForDefinition), holdLockJourney()],
  };

  await writeFile(outputPath, `${JSON.stringify(manifest, null, 2)}\n`);
  console.log(`Wrote ${outputPath}`);
}

void main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
