import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { ScreencastDefinitionFile, ScreencastJourney, ScreencastStep } from "@/scripts/screencast/lib/types";

const root = process.cwd();
const docsV3 = path.join(root, "docs", "v3");
const legacyManifestPath = path.join(docsV3, "journeys.screencast.v3.json");

type PortfolioCandidate = {
  id: string;
  name: string;
  layer: "P0" | "P1" | "P2";
  priority: "P0" | "P1" | "P2";
  audienceFit: string[];
  currentRealityLabel: string;
  proofLevel: ScreencastJourney["proofLevel"];
  overclaimRisk: string;
  caveat: string;
  proofPath: string[];
  captionShort: string;
  captionLong: string;
  presenterNotes: string[];
  customerSendable: boolean;
  primaryActor: string;
  additionalRoles: string[];
  tenant: string;
  roleKey: string;
  tenantSlug: string;
  startRoute: string;
  endState: string;
  fixtureId?: string;
  legacyJourneyIds: string[];
  sourceStepKeys?: string[];
  routeSteps?: Array<{
    route: string;
    screen: string;
    caption: string;
    expectedVisibleText?: string[];
    role?: string;
    roleKey?: string;
    tenant?: string;
    tenantSlug?: string;
    manualOrStatic?: boolean;
  }>;
};

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function stepKey(step: ScreencastStep) {
  return `${step.route}|${step.screen}|${step.step}`;
}

function renumberSteps(steps: ScreencastStep[], candidate: PortfolioCandidate) {
  return steps.map((step, index) => ({
    ...step,
    step: index + 1,
    id: `${candidate.id}-S${String(index + 1).padStart(2, "0")}`,
    role: candidate.primaryActor,
    roleKey: candidate.roleKey,
    tenant: candidate.tenant,
    tenantSlug: candidate.tenantSlug,
    screenshotName: `${candidate.id.toLowerCase()}-${String(index + 1).padStart(2, "0")}-${step.screenshotName}`,
  }));
}

function staticStep(input: NonNullable<PortfolioCandidate["routeSteps"]>[number], index: number): ScreencastStep {
  const screen = input.screen;
  return {
    step: index + 1,
    role: input.role ?? "Demo Actor",
    roleKey: input.roleKey,
    tenant: input.tenant ?? "AlphaVest Demo",
    tenantSlug: input.tenantSlug,
    route: input.route,
    screen,
    inputData: [],
    action: "Inspect route state",
    target: null,
    interaction: { type: "none" },
    navigation: "goto",
    dataRefs: [],
    caption: input.caption,
    expectedVisibleText: input.expectedVisibleText ?? [screen],
    expectedStateChange: "Route/static demo state is visible; no production workflow claim is made.",
    blockedActions: ["Unapproved advice release"],
    clientVisibility: "Controlled by demo route state and caveat",
    evidence: "Route/static evidence only unless linked to a handler proof.",
    audit: "No audit event claimed for route/static steps.",
    qaAssertion: `${screen} renders without spec chrome or unsafe advice claims.`,
    pauseMs: 1400,
    screenshotName: `${screen.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "step"}`,
    manualOrStatic: input.manualOrStatic ?? true,
    sourceProof: ["docs/v3/DEMO_JOURNEY_OPPORTUNITY_BACKLOG_V3.json"],
  };
}

function sourceSteps(legacyById: Map<string, ScreencastJourney>, candidate: PortfolioCandidate) {
  const selected: ScreencastStep[] = [];
  const requestedKeys = new Set(candidate.sourceStepKeys ?? []);

  for (const legacyId of candidate.legacyJourneyIds) {
    const legacy = legacyById.get(legacyId);
    if (!legacy) continue;
    for (const step of legacy.steps) {
      if (requestedKeys.size === 0 || requestedKeys.has(stepKey(step))) {
        selected.push(clone(step));
      }
    }
  }

  if (candidate.routeSteps?.length) {
    selected.push(...candidate.routeSteps.map(staticStep));
  }

  return renumberSteps(selected, candidate);
}

function buildJourney(legacyById: Map<string, ScreencastJourney>, candidate: PortfolioCandidate): ScreencastJourney {
  const steps = sourceSteps(legacyById, candidate);
  if (steps.length === 0) throw new Error(`No steps generated for ${candidate.id}`);

  return {
    id: candidate.id,
    name: candidate.name,
    portfolioLayer: candidate.layer,
    candidateId: candidate.id,
    legacyJourneyIds: candidate.legacyJourneyIds,
    demoPriority: candidate.priority,
    audienceFit: candidate.audienceFit,
    currentRealityLabel: candidate.currentRealityLabel,
    proofLevel: candidate.proofLevel,
    overclaimRisk: candidate.overclaimRisk,
    caveat: candidate.caveat,
    proofPath: candidate.proofPath,
    captionShort: candidate.captionShort,
    captionLong: candidate.captionLong,
    presenterNotes: candidate.presenterNotes,
    customerSendable: candidate.customerSendable,
    fixtureId: candidate.fixtureId,
    provisioning: candidate.fixtureId
      ? {
          mode: "database-fixture",
          fixtureId: candidate.fixtureId,
          resetStrategy: "base-seed",
          required: true,
          seedCommand: `pnpm screencast:seed-journey -- ${candidate.id} --fixture=${candidate.fixtureId}`,
          validates: ["fixture refs", "demo data state", "expected mutation context"],
        }
      : undefined,
    primaryActor: candidate.primaryActor,
    additionalRoles: candidate.additionalRoles,
    tenant: candidate.tenant,
    startRoute: candidate.startRoute,
    endState: candidate.endState,
    demoSession: {
      mode: "demo",
      defaultRoleKey: candidate.roleKey,
      defaultTenantSlug: candidate.tenantSlug,
    },
    queryParams: {},
    preconditions: [
      "Demo session mode is active",
      "No real customer data is used",
      candidate.caveat,
    ],
    demoData: [candidate.id, ...candidate.legacyJourneyIds],
    visibilityRules: [
      "No unapproved advice reaches the client",
      "Client visibility is controlled by compliance and route-specific caveats",
    ],
    complianceRules: [
      "Advisor approval alone is not enough",
      "Compliance release controls client visibility when advice-like content is involved",
    ],
    evidenceExpectations: candidate.proofPath,
    auditExpectations: [candidate.currentRealityLabel, candidate.proofLevel ?? "PL0"],
    riskNotes: [candidate.overclaimRisk, candidate.caveat],
    steps,
  };
}

function manifest(layer: "P0" | "P1" | "P2", journeys: ScreencastJourney[]): ScreencastDefinitionFile {
  return {
    schemaVersion: "3.1.0",
    engineMode: "ENGINE_MIX_V2_CODEX_V3_PROOF",
    outputRoot: "artifacts/screencasts",
    sourcePlaybook: "docs/v3/DEMO_VIDEO_IMPLEMENTATION_ROADMAP_V3.md",
    generatedFor: `AlphaVest WealthOS ${layer} portfolio screencast automation`,
    manifestId: `journeys.screencast.${layer.toLowerCase()}.v3`,
    portfolioLayer: layer,
    requiresPortfolioMetadata: true,
    speedProfiles: ["human-demo", "qa-fast"],
    journeys,
  };
}

const p0Candidates: PortfolioCandidate[] = [
  {
    id: "P0-01",
    name: "Platform Policy And No-Advice Baseline",
    layer: "P0",
    priority: "P0",
    audienceFit: ["customer", "executive", "compliance"],
    currentRealityLabel: "policy-frame-only",
    proofLevel: "PL2",
    overclaimRisk: "Viewer may assume policy and security settings were persisted by domain-specific handlers.",
    caveat: "This is a policy frame; dedicated j10.* handlers are required before claiming policy/security persistence.",
    proofPath: ["docs/v3/journeys.screencast.v3.json#J10", "docs/v3/DEMO_JOURNEY_UNIVERSE_AUDIT_V3.md"],
    captionShort: "AlphaVest starts with a no-unapproved-advice policy frame.",
    captionLong: "Platform policies frame the demo: advisor approval alone never releases advice to the client.",
    presenterNotes: ["Use this as narrative setup, not policy persistence proof."],
    customerSendable: true,
    primaryActor: "Platform Admin",
    additionalRoles: ["Compliance Officer", "Security Officer"],
    tenant: "Northbridge Family Office",
    roleKey: "admin",
    tenantSlug: "northbridge",
    startRoute: "/admin/platform",
    endState: "No-advice, evidence and redaction policies are framed before workflow starts.",
    fixtureId: "fixture-j10-platform-no-advice-baseline",
    legacyJourneyIds: ["J10"],
    sourceStepKeys: [],
  },
  {
    id: "P0-02",
    name: "Tenant Setup And Principal Invitation",
    layer: "P0",
    priority: "P0",
    audienceFit: ["customer", "operations", "executive"],
    currentRealityLabel: "test-proven",
    proofLevel: "PL5",
    overclaimRisk: "Viewer may assume real invitation delivery or real auth.",
    caveat: "Tenant setup is demo-action-backed; real invitation delivery and real auth remain out of scope.",
    proofPath: ["app/api/demo-workflow/route.ts#j06", "docs/v3/IMPLEMENTATION_QA_REPORT.md#phase-14-slice-4"],
    captionShort: "A client tenant is prepared before client work begins.",
    captionLong: "Tenant setup assigns team, policy and invitation state before the client journey starts.",
    presenterNotes: ["Keep real auth caveat visible in notes."],
    customerSendable: true,
    primaryActor: "Admin",
    additionalRoles: ["Client Success", "Principal"],
    tenant: "Morgan Family Office",
    roleKey: "admin",
    tenantSlug: "morgan",
    startRoute: "/admin/tenants",
    endState: "Principal invitation is ready in demo state.",
    fixtureId: "fixture-j06-tenant-onboarding",
    legacyJourneyIds: ["J06"],
    sourceStepKeys: [],
  },
  {
    id: "P0-03",
    name: "User Onboarding Consent And Role Confirmation",
    layer: "P0",
    priority: "P0",
    audienceFit: ["customer", "compliance", "operations"],
    currentRealityLabel: "route-static",
    proofLevel: "PL2",
    overclaimRisk: "Viewer may assume real login, MFA or identity verification.",
    caveat: "Onboarding screens are demo-state only; no real auth, MFA or identity provider is implemented.",
    proofPath: ["lib/route-registry.ts", "docs/v3/DEMO_JOURNEY_UNIVERSE_AUDIT_V3.md"],
    captionShort: "Onboarding shows consent and role acknowledgement in demo mode.",
    captionLong: "The invited-user flow demonstrates the privacy and role acknowledgement journey without real authentication.",
    presenterNotes: ["Say 'demo onboarding state', never 'real MFA'."],
    customerSendable: true,
    primaryActor: "Invited User",
    additionalRoles: ["Admin"],
    tenant: "Morgan Family Office",
    roleKey: "principal",
    tenantSlug: "morgan",
    startRoute: "/login",
    endState: "Role acknowledgement is visible as a demo onboarding state.",
    fixtureId: "fixture-j06-tenant-onboarding",
    legacyJourneyIds: ["J06"],
    routeSteps: [
      { route: "/login", screen: "Authentication Login", caption: "Authentication Login: start the invited-user demo flow.", expectedVisibleText: ["Authentication Login"], role: "Invited User", roleKey: "principal", tenant: "Morgan Family Office", tenantSlug: "morgan" },
      { route: "/mfa", screen: "Multi-Factor Authentication", caption: "Multi-Factor Authentication: MFA is shown as demo-state only.", expectedVisibleText: ["Multi-Factor Authentication"], role: "Invited User", roleKey: "principal", tenant: "Morgan Family Office", tenantSlug: "morgan" },
      { route: "/onboarding/invite", screen: "Invitation Acceptance", caption: "Invitation Acceptance: accept the demo invitation before entering tenant data.", expectedVisibleText: ["Invitation Acceptance"], role: "Invited User", roleKey: "principal", tenant: "Morgan Family Office", tenantSlug: "morgan" },
      { route: "/onboarding/identity", screen: "Identity Setup", caption: "Identity Setup: capture identity context without claiming real verification.", expectedVisibleText: ["Identity Setup"], role: "Invited User", roleKey: "principal", tenant: "Morgan Family Office", tenantSlug: "morgan" },
      { route: "/onboarding/consent", screen: "Consent and Privacy", caption: "Consent and Privacy: consent is explicit before role confirmation.", expectedVisibleText: ["Consent and Privacy"], role: "Invited User", roleKey: "principal", tenant: "Morgan Family Office", tenantSlug: "morgan" },
      { route: "/onboarding/role-confirmation", screen: "Role Confirmation", caption: "Role Confirmation: access is scoped before entering the workspace.", expectedVisibleText: ["Role Confirmation"], role: "Invited User", roleKey: "principal", tenant: "Morgan Family Office", tenantSlug: "morgan" }
    ],
  },
  {
    id: "P0-04",
    name: "Client Profile Documents And Data Quality",
    layer: "P0",
    priority: "P0",
    audienceFit: ["customer", "operations", "compliance"],
    currentRealityLabel: "test-proven",
    proofLevel: "PL5",
    overclaimRisk: "Viewer may assume real file upload or AI finality.",
    caveat: "Document/file handling is metadata-only demo proof; AI extraction remains human-reviewed.",
    proofPath: ["app/api/demo-workflow/route.ts#j04", "app/api/demo-workflow/route.ts#j09", "docs/v3/IMPLEMENTATION_QA_REPORT.md"],
    captionShort: "Trusted inputs enter through profile and document intake.",
    captionLong: "Client profile, family data and documents create controlled input states before advice workflow starts.",
    presenterNotes: ["Use this to explain evidence-backed inputs, not final advice."],
    customerSendable: true,
    primaryActor: "Family CFO",
    additionalRoles: ["Principal", "Analyst"],
    tenant: "Morgan Family Office",
    roleKey: "family_cfo",
    tenantSlug: "morgan",
    startRoute: "/portal",
    endState: "Profile and document inputs are ready for human review.",
    fixtureId: "fixture-j04-document-upload-verification",
    legacyJourneyIds: ["J09", "J04"],
    sourceStepKeys: [
      "/portal|Client Web Dashboard|1",
      "/client/profile|Client Profile|3",
      "/client/family-members|Family Members|4",
      "/relationships|Relationship Map|7",
      "/documents|Documents List|2",
      "/documents/upload|Document Upload|3",
      "/documents/extraction-review|Extraction Review|5",
      "/documents/verification-pending|Verification Pending|6"
    ],
  },
  {
    id: "P0-05",
    name: "Entities Wealth Map And Action Readiness",
    layer: "P0",
    priority: "P0",
    audienceFit: ["customer", "advisor", "operations"],
    currentRealityLabel: "test-proven",
    proofLevel: "PL5",
    overclaimRisk: "Viewer may assume action readiness bypasses evidence gates.",
    caveat: "Action readiness remains evidence-gated and demo-scoped.",
    proofPath: ["app/api/demo-workflow/route.ts#j05", "docs/v3/IMPLEMENTATION_QA_REPORT.md#phase-14-slice-7"],
    captionShort: "Structure and action boards stay evidence-gated.",
    captionLong: "Entity, wealth map and action states organize work but do not release unapproved advice.",
    presenterNotes: ["Keep blocked-ready proof for P2 if challenged."],
    customerSendable: true,
    primaryActor: "Principal",
    additionalRoles: ["Advisor", "Analyst"],
    tenant: "Summit Ridge Capital",
    roleKey: "principal",
    tenantSlug: "summit",
    startRoute: "/entities",
    endState: "Action readiness is visible but governed by evidence.",
    fixtureId: "fixture-j05-entity-wealth-action",
    legacyJourneyIds: ["J05"],
    sourceStepKeys: [],
  },
  {
    id: "P0-06",
    name: "Signal Request Data And Analyst Routing",
    layer: "P0",
    priority: "P0",
    audienceFit: ["customer", "advisor", "executive"],
    currentRealityLabel: "demo-action-executable",
    proofLevel: "PL4",
    overclaimRisk: "Viewer may assume the signal is client advice.",
    caveat: "Signal review remains internal and creates no client visibility.",
    proofPath: ["app/api/demo-workflow/route.ts#j01.requestData", "app/api/demo-workflow/route.ts#j01.routeToAdvisor"],
    captionShort: "A signal can request data and route internally.",
    captionLong: "Analysts can request missing data and route a package without making it client-visible.",
    presenterNotes: ["This is the start of the workflow, not client advice."],
    customerSendable: true,
    primaryActor: "Analyst",
    additionalRoles: ["System", "Senior Wealth Advisor"],
    tenant: "Northbridge Family Office",
    roleKey: "analyst",
    tenantSlug: "northbridge",
    startRoute: "/signals",
    endState: "Advisor review is queued, client visibility remains blocked.",
    fixtureId: "fixture-j01-signal-advisor-gate",
    legacyJourneyIds: ["J01"],
    sourceStepKeys: [
      "/signals|Signal Review|1",
      "/signals|Signal Review|2",
      "/workbench|Consultant Workbench|3",
      "/workbench/triggers/demo|Trigger Detail|4"
    ],
  },
  {
    id: "P0-07",
    name: "Advisor Approval Without Client Release",
    layer: "P0",
    priority: "P0",
    audienceFit: ["customer", "advisor", "compliance"],
    currentRealityLabel: "demo-action-executable",
    proofLevel: "PL4",
    overclaimRisk: "Viewer may assume advisor approval releases the recommendation.",
    caveat: "Advisor approval alone does not release anything to the client.",
    proofPath: ["app/api/demo-workflow/route.ts#j01.approveAdvisor", "lib/workflow-gate.ts"],
    captionShort: "Advisor approval is human review, not client release.",
    captionLong: "The advisor can approve the internal package, but compliance still controls client visibility.",
    presenterNotes: ["This is the strongest rule to repeat in sales demos."],
    customerSendable: true,
    primaryActor: "Senior Wealth Advisor",
    additionalRoles: ["Compliance Officer"],
    tenant: "Northbridge Family Office",
    roleKey: "senior_wealth_advisor",
    tenantSlug: "northbridge",
    startRoute: "/advisor-approval",
    endState: "Advisor approval is saved; client release remains blocked.",
    fixtureId: "fixture-j01-signal-advisor-gate",
    legacyJourneyIds: ["J01"],
    sourceStepKeys: [
      "/advisor-approval|Advisor Approval Queue|5",
      "/advisor-approval/demo|Advisor Approval Detail|6",
      "/decisions|Decision List|8"
    ],
  },
  {
    id: "P0-08",
    name: "Compliance Request Evidence Or Block Release",
    layer: "P0",
    priority: "P0",
    audienceFit: ["customer", "compliance", "executive"],
    currentRealityLabel: "test-proven",
    proofLevel: "PL5",
    overclaimRisk: "Viewer may miss the difference between request evidence and release.",
    caveat: "Request/block paths keep client visibility off.",
    proofPath: ["app/api/demo-workflow/route.ts#j02.requestEvidence", "app/api/demo-workflow/route.ts#j02.blockRelease", "docs/v3/IMPLEMENTATION_QA_REPORT.md#phase-14-slice-1"],
    captionShort: "Compliance can request evidence or block release.",
    captionLong: "Compliance is a release gate: missing evidence keeps the recommendation hidden from the client.",
    presenterNotes: ["Use this as the negative half of the release story."],
    customerSendable: true,
    primaryActor: "Compliance Officer",
    additionalRoles: ["Advisor", "Analyst"],
    tenant: "Morgan Family Office",
    roleKey: "compliance_officer",
    tenantSlug: "morgan",
    startRoute: "/compliance",
    endState: "Release is blocked until evidence is complete.",
    fixtureId: "fixture-j02-compliance-release-block",
    legacyJourneyIds: ["J02"],
    sourceStepKeys: [
      "/compliance|Compliance Queue|1",
      "/compliance/demo/review|Compliance Review Detail|2",
      "/compliance/demo/review|Compliance Review Detail|3",
      "/compliance/demo/block?state=block|Block Or Request Evidence|5"
    ],
  },
  {
    id: "P0-09",
    name: "Compliance Release To Client",
    layer: "P0",
    priority: "P0",
    audienceFit: ["customer", "compliance", "executive"],
    currentRealityLabel: "test-proven",
    proofLevel: "PL5",
    overclaimRisk: "Viewer may think release happens before compliance completes the gate.",
    caveat: "Client visibility is created only by compliance release after gate checks.",
    proofPath: ["app/api/demo-workflow/route.ts#j02.releaseClient", "lib/workflow-gate.ts", "docs/v3/IMPLEMENTATION_QA_REPORT.md#phase-14-slice-1"],
    captionShort: "Compliance release is the client-visibility switch.",
    captionLong: "Only after advisor approval, evidence and compliance release can the client see the decision.",
    presenterNotes: ["This clip should follow P0-08 in the 15/30 minute playlist."],
    customerSendable: true,
    primaryActor: "Compliance Officer",
    additionalRoles: ["Principal"],
    tenant: "Summit Ridge Capital",
    roleKey: "compliance_officer",
    tenantSlug: "summit",
    startRoute: "/compliance/demo/release",
    endState: "Client decision becomes visible after release.",
    fixtureId: "fixture-j02-compliance-release-block",
    legacyJourneyIds: ["J02"],
    sourceStepKeys: [
      "/compliance/demo/release?state=release|Release To Client|6",
      "/decisions|Decision List|8"
    ],
  },
  {
    id: "P0-10",
    name: "Client Decision And Evidence",
    layer: "P0",
    priority: "P0",
    audienceFit: ["customer", "client", "compliance"],
    currentRealityLabel: "test-proven",
    proofLevel: "PL5",
    overclaimRisk: "Viewer may miss that only released content is visible.",
    caveat: "Client decisions are demo transactions, not final financial/legal/tax advice.",
    proofPath: ["app/api/demo-workflow/route.ts#j03", "docs/v3/IMPLEMENTATION_QA_REPORT.md#phase-14-slice-2"],
    captionShort: "The client can decide only after release and can trace evidence.",
    captionLong: "Released decisions give the client action options and evidence access with audit trail.",
    presenterNotes: ["Defer/reject alternatives are P2 proof paths."],
    customerSendable: true,
    primaryActor: "Principal",
    additionalRoles: ["Family Council", "Compliance Officer"],
    tenant: "Bennett Family Office",
    roleKey: "principal",
    tenantSlug: "bennett",
    startRoute: "/decisions",
    endState: "Decision accepted and evidence is available.",
    fixtureId: "fixture-j03-client-decision-evidence",
    legacyJourneyIds: ["J03"],
    routeSteps: [
      { route: "/evidence", screen: "Evidence Vault", caption: "Evidence Vault: browse released proof before opening a record.", expectedVisibleText: ["Evidence"], role: "Principal", roleKey: "principal", tenant: "Bennett Family Office", tenantSlug: "bennett" }
    ],
    sourceStepKeys: [],
  },
  {
    id: "P0-11",
    name: "Export Redaction Approval And Download",
    layer: "P0",
    priority: "P0",
    audienceFit: ["customer", "compliance", "privacy"],
    currentRealityLabel: "metadata-only-export",
    proofLevel: "PL5",
    overclaimRisk: "Viewer may assume a real binary archive is generated.",
    caveat: "Export proof is metadata/package-manifest proof; no real binary archive is generated.",
    proofPath: ["app/api/demo-workflow/route.ts#j08", "lib/export-package-service.ts", "docs/v3/IMPLEMENTATION_QA_REPORT.md#phase-18"],
    captionShort: "Export is scoped, redacted, approved and audited.",
    captionLong: "Export packaging shows controlled scope, redaction and sharing without claiming real file generation.",
    presenterNotes: ["Use the metadata-only caveat when sharing externally."],
    customerSendable: true,
    primaryActor: "Principal",
    additionalRoles: ["Compliance Officer", "Privacy Officer"],
    tenant: "Summit Ridge Capital",
    roleKey: "principal",
    tenantSlug: "summit",
    startRoute: "/export/new",
    endState: "Redacted export package metadata is ready for controlled download/share.",
    fixtureId: "fixture-j08-export-redaction",
    legacyJourneyIds: ["J08"],
    sourceStepKeys: [],
  },
  {
    id: "P0-12",
    name: "Governance Access And Audit",
    layer: "P0",
    priority: "P0",
    audienceFit: ["customer", "security", "compliance"],
    currentRealityLabel: "test-proven",
    proofLevel: "PL5",
    overclaimRisk: "Viewer may assume production authorization is complete.",
    caveat: "Governance actions are demo authorization proof; real auth remains out of scope.",
    proofPath: ["app/api/demo-workflow/route.ts#j07", "tests/permission-engine.spec.ts", "docs/v3/IMPLEMENTATION_QA_REPORT.md#phase-14-slice-6"],
    captionShort: "Access changes are scoped, confirmed and audited.",
    captionLong: "Governance clips show invite, role confirmation, access approval and controlled audit export.",
    presenterNotes: ["Keep production-auth caveat visible."],
    customerSendable: true,
    primaryActor: "Principal",
    additionalRoles: ["Security Officer", "Compliance Officer"],
    tenant: "Northbridge Family Office",
    roleKey: "principal",
    tenantSlug: "northbridge",
    startRoute: "/governance/users",
    endState: "Access and audit controls are visible and scoped.",
    fixtureId: "fixture-j07-governance-access-audit",
    legacyJourneyIds: ["J07"],
    sourceStepKeys: [],
  },
];

const p1Candidates: PortfolioCandidate[] = [
  {
    id: "P1-01",
    name: "Evidence Vault Browse",
    layer: "P1",
    priority: "P1",
    audienceFit: ["compliance", "customer", "investor"],
    currentRealityLabel: "route-static",
    proofLevel: "PL2",
    overclaimRisk: "Viewer may assume every vault list action is persisted.",
    caveat: "The evidence index is route/static; detail view/download proof is in J03/P1-15.",
    proofPath: ["lib/route-registry.ts", "app/api/demo-workflow/route.ts#j03.viewEvidenceRecord"],
    captionShort: "Evidence is browseable before opening a record.",
    captionLong: "The evidence vault frames proof access; detailed view/download audit uses the J03 handler path.",
    presenterNotes: ["Use together with P1-15 for audit proof."],
    customerSendable: false,
    primaryActor: "Principal",
    additionalRoles: ["Compliance Officer"],
    tenant: "Bennett Family Office",
    roleKey: "principal",
    tenantSlug: "bennett",
    startRoute: "/evidence",
    endState: "Evidence record detail can be opened from vault context.",
    fixtureId: "fixture-j03-client-decision-evidence",
    legacyJourneyIds: ["J03"],
    routeSteps: [
      { route: "/evidence", screen: "Evidence Vault", caption: "Evidence Vault: browse proof records in a role-scoped context.", expectedVisibleText: ["Evidence"], role: "Principal", roleKey: "principal", tenant: "Bennett Family Office", tenantSlug: "bennett" },
      { route: "/evidence/demo", screen: "Evidence Record Detail", caption: "Evidence Record Detail: open the proof package used by the client decision.", expectedVisibleText: ["Evidence"], role: "Principal", roleKey: "principal", tenant: "Bennett Family Office", tenantSlug: "bennett" }
    ],
  },
  {
    id: "P1-15",
    name: "Evidence Download Audited",
    layer: "P1",
    priority: "P1",
    audienceFit: ["compliance", "investor"],
    currentRealityLabel: "demo-action-executable",
    proofLevel: "PL4",
    overclaimRisk: "Viewer may assume unrestricted evidence download.",
    caveat: "Evidence access remains role-scoped and demo-action-backed.",
    proofPath: ["app/api/demo-workflow/route.ts#j03.downloadEvidence", "docs/v3/IMPLEMENTATION_QA_REPORT.md#phase-14-slice-2"],
    captionShort: "Evidence access is audited.",
    captionLong: "Opening and downloading a record creates an audit trail in the demo workflow.",
    presenterNotes: ["Good follow-up after P0-10."],
    customerSendable: false,
    primaryActor: "Principal",
    additionalRoles: ["Compliance Officer"],
    tenant: "Bennett Family Office",
    roleKey: "principal",
    tenantSlug: "bennett",
    startRoute: "/evidence/demo",
    endState: "Evidence download audit is captured.",
    fixtureId: "fixture-j03-client-decision-evidence",
    legacyJourneyIds: ["J03"],
    sourceStepKeys: ["/evidence/demo|Evidence Record Detail|7"],
  },
  {
    id: "P1-16",
    name: "Mobile Safe Next Step",
    layer: "P1",
    priority: "P1",
    audienceFit: ["customer", "client"],
    currentRealityLabel: "route-static",
    proofLevel: "PL2",
    overclaimRisk: "Viewer may assume mobile has full production parity.",
    caveat: "Mobile is route/static client-safe proof for demo; no real mobile auth is claimed.",
    proofPath: ["lib/route-registry.ts", "docs/v3/DEMO_JOURNEY_UNIVERSE_AUDIT_V3.md"],
    captionShort: "Mobile shows safe next steps, not unreleased advice.",
    captionLong: "The mobile surface is useful for customer demos, but remains demo-route proof.",
    presenterNotes: ["Use if the audience cares about client experience."],
    customerSendable: false,
    primaryActor: "Principal",
    additionalRoles: ["Family Member"],
    tenant: "Morgan Family Office",
    roleKey: "principal",
    tenantSlug: "morgan",
    startRoute: "/mobile",
    endState: "Client-safe mobile state is visible.",
    legacyJourneyIds: ["J09", "J04"],
    routeSteps: [
      { route: "/mobile", screen: "Mobile Client Workspace", caption: "Mobile Client Workspace: show safe next steps without unreleased recommendations.", expectedVisibleText: ["Mobile"], role: "Principal", roleKey: "principal", tenant: "Morgan Family Office", tenantSlug: "morgan" }
    ],
  },
  {
    id: "P1-02",
    name: "Communication Path Selection",
    layer: "P1",
    priority: "P1",
    audienceFit: ["operations", "client success", "investor"],
    currentRealityLabel: "route-static",
    proofLevel: "PL2",
    overclaimRisk: "Viewer may assume message persistence.",
    caveat: "Communication routes are route/static until dedicated message/call handlers are added.",
    proofPath: ["lib/route-registry.ts", "docs/v3/DEMO_JOURNEY_UNIVERSE_AUDIT_V3.md"],
    captionShort: "Human escalation is part of the digital-first workflow.",
    captionLong: "Communication path selection shows how digital work can escalate without releasing advice.",
    presenterNotes: ["Do not claim message persistence."],
    customerSendable: false,
    primaryActor: "Advisor",
    additionalRoles: ["Client Success"],
    tenant: "Northbridge Family Office",
    roleKey: "senior_wealth_advisor",
    tenantSlug: "northbridge",
    startRoute: "/communication",
    endState: "Communication escalation path is visible.",
    legacyJourneyIds: ["J01"],
    routeSteps: [
      { route: "/communication", screen: "Communication Center", caption: "Communication Center: select a safe contact path after internal review.", expectedVisibleText: ["Communication"], role: "Advisor", roleKey: "senior_wealth_advisor", tenant: "Northbridge Family Office", tenantSlug: "northbridge" },
      { route: "/communication/call-trigger", screen: "Call Trigger Matrix", caption: "Call Trigger Matrix: escalation rules stay human-reviewed and controlled.", expectedVisibleText: ["Call"], role: "Advisor", roleKey: "senior_wealth_advisor", tenant: "Northbridge Family Office", tenantSlug: "northbridge" }
    ],
  },
  {
    id: "P1-03",
    name: "Call Trigger Matrix",
    layer: "P1",
    priority: "P1",
    audienceFit: ["operations", "compliance"],
    currentRealityLabel: "route-static",
    proofLevel: "PL2",
    overclaimRisk: "Viewer may assume call outcome persistence.",
    caveat: "Call trigger is route/static unless a future handler records call outcomes.",
    proofPath: ["lib/route-registry.ts"],
    captionShort: "Escalation rules make human review visible.",
    captionLong: "The call-trigger route explains when digital work should become human escalation.",
    presenterNotes: ["Good appendix clip; not core P0."],
    customerSendable: false,
    primaryActor: "Advisor",
    additionalRoles: ["Client Success"],
    tenant: "Northbridge Family Office",
    roleKey: "senior_wealth_advisor",
    tenantSlug: "northbridge",
    startRoute: "/communication/call-trigger",
    endState: "Call escalation matrix is visible.",
    legacyJourneyIds: ["J01"],
    routeSteps: [
      { route: "/communication/call-trigger", screen: "Call Trigger Matrix", caption: "Call Trigger Matrix: inspect escalation triggers without releasing advice.", expectedVisibleText: ["Call"], role: "Advisor", roleKey: "senior_wealth_advisor", tenant: "Northbridge Family Office", tenantSlug: "northbridge" }
    ],
  },
  {
    id: "P1-13",
    name: "Permission Matrix And Second Confirmation",
    layer: "P1",
    priority: "P1",
    audienceFit: ["security", "compliance", "investor"],
    currentRealityLabel: "test-proven",
    proofLevel: "PL5",
    overclaimRisk: "Viewer may assume complete production RBAC.",
    caveat: "Permission proof is deterministic demo authorization, not real identity-provider auth.",
    proofPath: ["tests/permission-engine.spec.ts", "app/api/demo-workflow/route.ts#j07.saveRoleChanges"],
    captionShort: "Sensitive role changes require confirmation.",
    captionLong: "Role and access changes show scoped governance with second confirmation and audit proof.",
    presenterNotes: ["Use for diligence, not core P0."],
    customerSendable: false,
    primaryActor: "Security Officer",
    additionalRoles: ["Principal", "Compliance Officer"],
    tenant: "Northbridge Family Office",
    roleKey: "principal",
    tenantSlug: "northbridge",
    startRoute: "/governance/roles",
    endState: "Sensitive role confirmation is visible.",
    fixtureId: "fixture-j07-governance-access-audit",
    legacyJourneyIds: ["J07"],
    sourceStepKeys: [
      "/governance/roles?state=confirm|Role Management|3",
      "/governance/access-requests?state=approval|Access Requests|5",
      "/governance/audit-history?state=drawer|Access Audit History|7"
    ],
  },
];

const p2Candidates: PortfolioCandidate[] = [
  {
    id: "P2-01",
    name: "Principal Cannot Release Recommendation",
    layer: "P2",
    priority: "P2",
    audienceFit: ["compliance", "investor"],
    currentRealityLabel: "test-proven",
    proofLevel: "PL5",
    overclaimRisk: "Viewer may confuse denial proof with production authorization.",
    caveat: "This is deterministic demo permission proof, not real auth.",
    proofPath: ["tests/permission-engine.spec.ts"],
    captionShort: "Principals cannot release recommendations.",
    captionLong: "Release authority remains with compliance even when a principal can view client surfaces.",
    presenterNotes: ["Promote to video only for compliance/investor diligence."],
    customerSendable: false,
    primaryActor: "Principal",
    additionalRoles: ["Compliance Officer"],
    tenant: "Bennett Family Office",
    roleKey: "principal",
    tenantSlug: "bennett",
    startRoute: "/decisions",
    endState: "Release attempt is denied in permission proof.",
    legacyJourneyIds: ["J02", "J03"],
    routeSteps: [
      { route: "/decisions", screen: "Decision List", caption: "Decision List: release authority remains outside the principal role.", expectedVisibleText: ["Decision"], role: "Principal", roleKey: "principal", tenant: "Bennett Family Office", tenantSlug: "bennett" },
      { route: "/compliance/demo/release", screen: "Release To Client", caption: "Release To Client: compliance release is not a principal action.", expectedVisibleText: ["Release"], role: "Principal", roleKey: "principal", tenant: "Bennett Family Office", tenantSlug: "bennett" }
    ],
  },
  {
    id: "P2-02",
    name: "Cross Tenant Access Denied",
    layer: "P2",
    priority: "P2",
    audienceFit: ["security", "compliance"],
    currentRealityLabel: "test-proven",
    proofLevel: "PL5",
    overclaimRisk: "Viewer may assume this tests every object-level permission.",
    caveat: "This proves top demo tenant-isolation cases, not exhaustive production access control.",
    proofPath: ["tests/permission-engine.spec.ts"],
    captionShort: "Cross-tenant access is denied.",
    captionLong: "Tenant isolation is demonstrated through permission tests and denial audit behavior.",
    presenterNotes: ["Prefer as proof artifact over video."],
    customerSendable: false,
    primaryActor: "External Advisor",
    additionalRoles: ["Security Officer"],
    tenant: "Northbridge Family Office",
    roleKey: "external_advisor",
    tenantSlug: "northbridge",
    startRoute: "/governance/audit-history",
    endState: "Cross-tenant access stays denied.",
    legacyJourneyIds: ["J07"],
    routeSteps: [
      { route: "/governance/audit-history", screen: "Access Audit History", caption: "Access Audit History: tenant isolation is validated by tests, not route access alone.", expectedVisibleText: ["Audit"], role: "External Advisor", roleKey: "external_advisor", tenant: "Northbridge Family Office", tenantSlug: "northbridge" }
    ],
  },
  {
    id: "P2-05",
    name: "Unsupported File Upload Blocked",
    layer: "P2",
    priority: "P2",
    audienceFit: ["compliance", "operations"],
    currentRealityLabel: "test-proven",
    proofLevel: "PL5",
    overclaimRisk: "Viewer may assume malware scanning/object storage exists.",
    caveat: "File proof is metadata validation only; no malware scan or object storage claim.",
    proofPath: ["tests/file-export-realism.spec.ts"],
    captionShort: "Unsafe file metadata is blocked.",
    captionLong: "Document intake validates metadata before evidence or extraction claims are made.",
    presenterNotes: ["Use if file trust is challenged."],
    customerSendable: false,
    primaryActor: "Family CFO",
    additionalRoles: ["Analyst"],
    tenant: "Morgan Family Office",
    roleKey: "family_cfo",
    tenantSlug: "morgan",
    startRoute: "/documents/upload",
    endState: "Unsupported file metadata is denied by tests.",
    legacyJourneyIds: ["J04"],
    sourceStepKeys: ["/documents/upload|Document Upload|3"],
  },
  {
    id: "P2-03",
    name: "External Advisor Export Denied",
    layer: "P2",
    priority: "P2",
    audienceFit: ["security", "privacy", "compliance"],
    currentRealityLabel: "test-proven",
    proofLevel: "PL5",
    overclaimRisk: "Viewer may assume every delegated-advisor edge case is covered.",
    caveat: "This is a top negative permission proof; do not claim exhaustive production authorization.",
    proofPath: ["tests/permission-engine.spec.ts", "tests/file-export-realism.spec.ts"],
    captionShort: "External advisors cannot export beyond their scope.",
    captionLong: "Export access remains scoped by tenant, role and approval state before any sharing claim is made.",
    presenterNotes: ["Keep this as QA-first unless a security buyer asks for the visual clip."],
    customerSendable: false,
    primaryActor: "External Advisor",
    additionalRoles: ["Privacy Officer", "Compliance Officer"],
    tenant: "Summit Ridge Capital",
    roleKey: "external_advisor",
    tenantSlug: "summit",
    startRoute: "/export/demo/preview",
    endState: "External advisor export access is denied by permission proof.",
    fixtureId: "fixture-j08-export-redaction",
    legacyJourneyIds: ["J08"],
    routeSteps: [
      { route: "/export/demo/preview", screen: "Export Preview", caption: "Export Preview: external-advisor export scope stays denied without approval.", expectedVisibleText: ["Export"], role: "External Advisor", roleKey: "external_advisor", tenant: "Summit Ridge Capital", tenantSlug: "summit" }
    ],
  },
  {
    id: "P2-06",
    name: "Low Confidence Extraction Requires Human Review",
    layer: "P2",
    priority: "P2",
    audienceFit: ["operations", "compliance", "ethics"],
    currentRealityLabel: "route-static",
    proofLevel: "PL2",
    overclaimRisk: "Viewer may assume AI extraction is autonomous or final.",
    caveat: "Low-confidence extraction is a demo-state route; human review is the claim, not autonomous AI accuracy.",
    proofPath: ["docs/v3/DATA_MODEL_V3.md", "docs/v3/DEMO_JOURNEY_UNIVERSE_AUDIT_V3.md"],
    captionShort: "Low-confidence extraction stays human-reviewed.",
    captionLong: "Document extraction can be shown as an assistive input flow where uncertain data is held for review.",
    presenterNotes: ["Use this to answer AI-safety questions, not as an ML-performance proof."],
    customerSendable: false,
    primaryActor: "Analyst",
    additionalRoles: ["Family CFO"],
    tenant: "Morgan Family Office",
    roleKey: "analyst",
    tenantSlug: "morgan",
    startRoute: "/documents/extraction-review",
    endState: "Low-confidence fields remain pending review.",
    fixtureId: "fixture-j04-document-upload-verification",
    legacyJourneyIds: ["J04"],
    routeSteps: [
      { route: "/documents/extraction-review?state=low-confidence", screen: "Extraction Review", caption: "Extraction Review: low-confidence data is held for human confirmation.", expectedVisibleText: ["Extraction"], role: "Analyst", roleKey: "analyst", tenant: "Morgan Family Office", tenantSlug: "morgan" }
    ],
  },
  {
    id: "P2-09",
    name: "Client Defers Decision",
    layer: "P2",
    priority: "P2",
    audienceFit: ["client", "ethics", "compliance"],
    currentRealityLabel: "test-proven",
    proofLevel: "PL5",
    overclaimRisk: "Viewer may think accept is the only client path.",
    caveat: "Client decision alternatives are demo transactions, not financial advice.",
    proofPath: ["app/api/demo-workflow/route.ts#j03.deferDecision", "docs/v3/IMPLEMENTATION_QA_REPORT.md#phase-14-slice-2"],
    captionShort: "The client can defer.",
    captionLong: "Client agency includes defer, reject and request-more-information alternatives.",
    presenterNotes: ["Good ethics/fairness proof."],
    customerSendable: false,
    primaryActor: "Principal",
    additionalRoles: ["Family Council"],
    tenant: "Bennett Family Office",
    roleKey: "principal",
    tenantSlug: "bennett",
    startRoute: "/decisions/demo",
    endState: "Decision is deferred in demo proof.",
    fixtureId: "fixture-j03-client-decision-evidence",
    legacyJourneyIds: ["J03"],
    sourceStepKeys: ["/decisions/demo?state=approval|Digital Decision Room|4"],
  },
  {
    id: "P2-10",
    name: "Client Rejects Decision",
    layer: "P2",
    priority: "P2",
    audienceFit: ["client", "ethics", "compliance"],
    currentRealityLabel: "route-static",
    proofLevel: "PL2",
    overclaimRisk: "Viewer may think decision flow optimizes only for acceptance.",
    caveat: "Reject state is demo-route proof; persistence needs a dedicated negative-path handler before claiming workflow completion.",
    proofPath: ["docs/v3/DEMO_JOURNEY_UNIVERSE_AUDIT_V3.md", "app/api/demo-workflow/route.ts#j03"],
    captionShort: "The client can say no.",
    captionLong: "A trustworthy decision workflow must support rejection as clearly as acceptance.",
    presenterNotes: ["This is useful for ethics/fairness, but not a core sales clip yet."],
    customerSendable: false,
    primaryActor: "Principal",
    additionalRoles: ["Family Council", "Advisor"],
    tenant: "Bennett Family Office",
    roleKey: "principal",
    tenantSlug: "bennett",
    startRoute: "/decisions/demo",
    endState: "Reject alternative is visible as a demo state.",
    fixtureId: "fixture-j03-client-decision-evidence",
    legacyJourneyIds: ["J03"],
    routeSteps: [
      { route: "/decisions/demo?state=reject", screen: "Digital Decision Room", caption: "Digital Decision Room: rejection remains a valid client outcome.", expectedVisibleText: ["Decision"], role: "Principal", roleKey: "principal", tenant: "Bennett Family Office", tenantSlug: "bennett" }
    ],
  },
  {
    id: "P2-11",
    name: "Export Without Approval Blocked",
    layer: "P2",
    priority: "P2",
    audienceFit: ["privacy", "compliance"],
    currentRealityLabel: "test-proven",
    proofLevel: "PL5",
    overclaimRisk: "Viewer may assume download is always available.",
    caveat: "Export download requires approval/redaction and remains metadata-only demo proof.",
    proofPath: ["lib/export-package-service.ts", "tests/file-export-realism.spec.ts"],
    captionShort: "Export is blocked until controls are satisfied.",
    captionLong: "Export proof includes approval, redaction and manifest constraints before sharing.",
    presenterNotes: ["Pair with P0-11 if challenged."],
    customerSendable: false,
    primaryActor: "Principal",
    additionalRoles: ["Compliance Officer"],
    tenant: "Summit Ridge Capital",
    roleKey: "principal",
    tenantSlug: "summit",
    startRoute: "/export/demo/preview",
    endState: "Export remains blocked until approval controls pass.",
    fixtureId: "fixture-j08-export-redaction",
    legacyJourneyIds: ["J08"],
    sourceStepKeys: ["/export/demo/preview?state=approval|Export Preview|4"],
  },
  {
    id: "P2-12",
    name: "Export Share Link Expires Or Is Revoked",
    layer: "P2",
    priority: "P2",
    audienceFit: ["privacy", "compliance", "security"],
    currentRealityLabel: "route-static",
    proofLevel: "PL2",
    overclaimRisk: "Viewer may assume full secure-link lifecycle implementation.",
    caveat: "Share expiry/revoke is a route/static proof candidate until a dedicated export-share handler exists.",
    proofPath: ["docs/v3/DEMO_JOURNEY_UNIVERSE_AUDIT_V3.md", "lib/export-package-service.ts"],
    captionShort: "Export sharing must be revocable.",
    captionLong: "Privacy-safe export delivery needs a visible expiry or revoke path before external sharing is customer-sendable.",
    presenterNotes: ["Use as a roadmap-proof clip, not as completed workflow proof."],
    customerSendable: false,
    primaryActor: "Privacy Officer",
    additionalRoles: ["Principal", "Compliance Officer"],
    tenant: "Summit Ridge Capital",
    roleKey: "privacy_officer",
    tenantSlug: "summit",
    startRoute: "/export/demo/download",
    endState: "Share expiry/revoke is visible as a proof candidate.",
    fixtureId: "fixture-j08-export-redaction",
    legacyJourneyIds: ["J08"],
    routeSteps: [
      { route: "/export/demo/download?state=expired", screen: "Export Download", caption: "Export Download: shared export access can be framed as expiring or revoked.", expectedVisibleText: ["Export"], role: "Privacy Officer", roleKey: "privacy_officer", tenant: "Summit Ridge Capital", tenantSlug: "summit" }
    ],
  },
  {
    id: "P2-13",
    name: "Access Request Denied Or Revoked",
    layer: "P2",
    priority: "P2",
    audienceFit: ["security", "compliance"],
    currentRealityLabel: "demo-action-executable",
    proofLevel: "PL4",
    overclaimRisk: "Viewer may assume deny/revoke is fully productized.",
    caveat: "Access negative path is a proof candidate; keep as QA-first unless implemented end-to-end.",
    proofPath: ["app/api/demo-workflow/route.ts#j07", "tests/permission-engine.spec.ts"],
    captionShort: "Access can be denied or revoked.",
    captionLong: "Governance proof must include removing access, not only granting it.",
    presenterNotes: ["Promote later if governance diligence requires visual proof."],
    customerSendable: false,
    primaryActor: "Principal",
    additionalRoles: ["Security Officer"],
    tenant: "Northbridge Family Office",
    roleKey: "principal",
    tenantSlug: "northbridge",
    startRoute: "/governance/access-requests",
    endState: "Access denial/revoke path is treated as QA-first proof.",
    fixtureId: "fixture-j07-governance-access-audit",
    legacyJourneyIds: ["J07"],
    sourceStepKeys: ["/governance/access-requests?state=approval|Access Requests|4"],
  },
];

async function main() {
  const legacy = JSON.parse(await readFile(legacyManifestPath, "utf8")) as ScreencastDefinitionFile;
  const legacyById = new Map(legacy.journeys.map((journey) => [journey.id, journey]));
  const p0 = manifest("P0", p0Candidates.map((candidate) => buildJourney(legacyById, candidate)));
  const p1 = manifest("P1", p1Candidates.map((candidate) => buildJourney(legacyById, candidate)));
  const p2 = manifest("P2", p2Candidates.map((candidate) => buildJourney(legacyById, candidate)));

  const p3Proof = {
    schemaVersion: "1.0.0",
    generatedAt: "2026-06-16",
    purpose: "P3 proof families are QA/report artifacts, not video manifests by default.",
    proofFamilies: [
      { id: "P3-01", name: "63-route smoke coverage", command: "pnpm test:route-smoke" },
      { id: "P3-02", name: "route x state x role matrix", command: "manual/generated matrix from route registry and backlog" },
      { id: "P3-03", name: "permission denial matrix", command: "pnpm test:permissions" },
      { id: "P3-04", name: "evidence/audit lifecycle matrix", command: "manual/generated matrix from handlers and QA report" },
      { id: "P3-05", name: "visual contract bundle", command: "pnpm visual:contract" }
    ],
    overclaimGuard: "P3 artifacts prove coverage and safety boundaries; they are not customer workflow videos."
  };

  await mkdir(docsV3, { recursive: true });
  await writeFile(path.join(docsV3, "journeys.screencast.p0.v3.json"), `${JSON.stringify(p0, null, 2)}\n`);
  await writeFile(path.join(docsV3, "journeys.screencast.p1.v3.json"), `${JSON.stringify(p1, null, 2)}\n`);
  await writeFile(path.join(docsV3, "journeys.screencast.p2.v3.json"), `${JSON.stringify(p2, null, 2)}\n`);
  await writeFile(path.join(docsV3, "DEMO_P3_PROOF_FAMILIES_V3.json"), `${JSON.stringify(p3Proof, null, 2)}\n`);
}

void main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
