export type Wp15CoverageStatus = "BLOCKED" | "CONFLICTING" | "COVERED" | "MISSING" | "PARTIAL";

export type Wp15CoverageEntry = {
  blocksV096Acceptance: boolean;
  category: "P0_SAFETY" | "TRUE_UX" | "SCOPE_CONTROL" | "PROOF_ORCHESTRATION";
  evidence: string;
  gateId: string;
  nonClaim: string;
  ownerWp: string;
  proofFiles: string[];
  status: Wp15CoverageStatus;
  title: string;
};

export const wp15RequiredGateIds = [
  "WP15-G01-MAPPED-ACTOR",
  "WP15-G02-CROSS-TENANT-DENIAL",
  "WP15-G03-ROLE-ACTION-PAYLOAD-SEPARATION",
  "WP15-G04-CLIENT-VISIBILITY-FAIL-CLOSED",
  "WP15-G05-AI-DRAFT-INTERNAL-ONLY",
  "WP15-G06-NO-UNAPPROVED-ADVICE",
  "WP15-G07-ADVISOR-NOT-RELEASE",
  "WP15-G08-COMPLIANCE-RELEASE-GATE",
  "WP15-G09-UPLOAD-NOT-SUFFICIENCY",
  "WP15-G10-EVIDENCE-SUFFICIENCY-REVIEWED",
  "WP15-G11-AUDIT-PERSISTENCE",
  "WP15-G12-AUDIT-FAIL-CLOSED",
  "WP15-G13-EXPORT-REDACTION",
  "WP15-G14-EXPORT-LIFECYCLE-SEPARATION",
  "WP15-G15-ADMIN-NON-BYPASS",
  "WP15-G16-API-ERROR-SAFETY",
  "WP15-G17-JOURNEY-FIRST-IA",
  "WP15-G18-PAGE-JOB-HEADER",
  "WP15-G19-DENSITY-CONTRACT",
  "WP15-G20-ONE-PRIMARY-CTA",
  "WP15-G21-PRIMITIVE-LIFECYCLE",
  "WP15-G22-A11Y-FOCUS-STATUS",
  "WP15-G23-NO-OVERCLAIM-COPY",
  "WP15-G24-STATUS-CHIP-NOT-GATE-PROOF",
  "WP15-G25-P1-HOLD-NOT-ELEVATED",
  "WP15-G26-POSITIVE-JOURNEY-SPINE",
  "WP15-G27-WP15-EVIDENCE-HANDOFF",
] as const;

export const wp15CoverageMatrix: Wp15CoverageEntry[] = [
  {
    blocksV096Acceptance: false,
    category: "P0_SAFETY",
    evidence: "Strict demo sessions reject unknown role/tenant and map actor, tenant and role before proof starts.",
    gateId: "WP15-G01-MAPPED-ACTOR",
    nonClaim: "Demo session proof is not production authentication.",
    ownerWp: "WP13/WP15",
    proofFiles: ["tests/providerless-scope.spec.ts", "tests/e2e/e2e-journey-proof-ws00-ws05.spec.ts"],
    status: "COVERED",
    title: "Mapped user / tenant / role context",
  },
  {
    blocksV096Acceptance: false,
    category: "P0_SAFETY",
    evidence: "Permission and projection tests deny switched tenant context and wrong tenant payload access.",
    gateId: "WP15-G02-CROSS-TENANT-DENIAL",
    nonClaim: "Route shell availability is not payload authorization.",
    ownerWp: "WP13/WP15",
    proofFiles: ["tests/permission-engine.spec.ts", "tests/providerless-scope.spec.ts"],
    status: "COVERED",
    title: "Cross-tenant denial",
  },
  {
    blocksV096Acceptance: false,
    category: "P0_SAFETY",
    evidence: "Route, action and payload decisions are asserted independently, including object-scope mismatch.",
    gateId: "WP15-G03-ROLE-ACTION-PAYLOAD-SEPARATION",
    nonClaim: "Being able to view a route does not grant mutation or hidden payload rights.",
    ownerWp: "WP09/WP13/WP15",
    proofFiles: ["tests/providerless-scope.spec.ts", "tests/permission-engine.spec.ts"],
    status: "COVERED",
    title: "Role/action/payload separation",
  },
  {
    blocksV096Acceptance: false,
    category: "P0_SAFETY",
    evidence: "Client projection tests return empty payloads before release and only client-safe summaries after release.",
    gateId: "WP15-G04-CLIENT-VISIBILITY-FAIL-CLOSED",
    nonClaim: "Client-safe projection is not client acceptance.",
    ownerWp: "WP07/WP15",
    proofFiles: ["tests/client-visibility-projection.spec.ts", "tests/true-ux-client-projection.spec.ts"],
    status: "COVERED",
    title: "Client visibility fail-closed",
  },
  {
    blocksV096Acceptance: false,
    category: "P0_SAFETY",
    evidence: "AI Draft, internal rationale, assumptions and compliance notes are blocked from client/export paths.",
    gateId: "WP15-G05-AI-DRAFT-INTERNAL-ONLY",
    nonClaim: "Internal analyst visibility does not mean client-safe advice.",
    ownerWp: "WP04/WP07/WP15",
    proofFiles: ["tests/p0-acceptance.spec.ts", "tests/true-ux-p0-safety.spec.ts", "tests/export-safety.spec.ts"],
    status: "COVERED",
    title: "AI Draft internal-only",
  },
  {
    blocksV096Acceptance: false,
    category: "P0_SAFETY",
    evidence: "Workflow gates and projection tests keep unreleased/advisor-only states out of client-visible payloads.",
    gateId: "WP15-G06-NO-UNAPPROVED-ADVICE",
    nonClaim: "Advisor review is not advice release.",
    ownerWp: "WP05/WP06/WP15",
    proofFiles: ["tests/workflow-gate.spec.ts", "tests/true-ux-p0-safety.spec.ts"],
    status: "COVERED",
    title: "No unapproved advice reaches client",
  },
  {
    blocksV096Acceptance: false,
    category: "P0_SAFETY",
    evidence: "Advisor-approved states still miss compliance release and released recommendation status.",
    gateId: "WP15-G07-ADVISOR-NOT-RELEASE",
    nonClaim: "Advisor approval alone never unlocks client visibility.",
    ownerWp: "WP05/WP12/WP15",
    proofFiles: ["tests/p0-acceptance.spec.ts", "tests/true-ux-p0-safety.spec.ts", "tests/ui-state-boundaries.spec.ts"],
    status: "COVERED",
    title: "Advisor approval is not compliance release",
  },
  {
    blocksV096Acceptance: false,
    category: "P0_SAFETY",
    evidence: "Compliance release gates require advisor, evidence, permission and audit-related preconditions.",
    gateId: "WP15-G08-COMPLIANCE-RELEASE-GATE",
    nonClaim: "Compliance release does not imply client acceptance.",
    ownerWp: "WP06/WP15",
    proofFiles: ["tests/workflow-gate.spec.ts", "tests/confirmation-lifecycle.spec.ts"],
    status: "COVERED",
    title: "Compliance release gate",
  },
  {
    blocksV096Acceptance: false,
    category: "P0_SAFETY",
    evidence: "Upload-created evidence remains pending review and blocks release/export/client visibility.",
    gateId: "WP15-G09-UPLOAD-NOT-SUFFICIENCY",
    nonClaim: "Upload success is only intake proof.",
    ownerWp: "WP03/WP12/WP15",
    proofFiles: ["tests/document-upload-flow.spec.ts", "tests/p0-acceptance.spec.ts", "tests/true-ux-p0-safety.spec.ts"],
    status: "COVERED",
    title: "Upload is not evidence sufficiency",
  },
  {
    blocksV096Acceptance: false,
    category: "P0_SAFETY",
    evidence: "Only reviewed, accepted, current and scoped evidence can support release gates.",
    gateId: "WP15-G10-EVIDENCE-SUFFICIENCY-REVIEWED",
    nonClaim: "Evidence sufficiency is not inferred from document presence.",
    ownerWp: "WP03/WP15",
    proofFiles: ["tests/evidence-review-api.spec.ts", "tests/e2e/e2e-journey-proof-ws00-ws05.spec.ts"],
    status: "COVERED",
    title: "Evidence sufficiency requires review/linking",
  },
  {
    blocksV096Acceptance: false,
    category: "P0_SAFETY",
    evidence: "Critical gates require persisted audit references or source-backed DB read models.",
    gateId: "WP15-G11-AUDIT-PERSISTENCE",
    nonClaim: "Visual audit rows are not persistence proof.",
    ownerWp: "WP08/WP15",
    proofFiles: ["tests/phase6-audit-persistence.spec.ts", "tests/true-ux-audit-surface.spec.ts"],
    status: "COVERED",
    title: "Audit persistence proof",
  },
  {
    blocksV096Acceptance: false,
    category: "P0_SAFETY",
    evidence: "Audit guard and export workflow tests block critical actions when audit persistence is unavailable.",
    gateId: "WP15-G12-AUDIT-FAIL-CLOSED",
    nonClaim: "A pending audit display is not sufficient to continue.",
    ownerWp: "WP08/WP15",
    proofFiles: ["tests/audit-fail-closed.spec.ts", "tests/phase8-export-workflow-api.spec.ts"],
    status: "COVERED",
    title: "Audit failure blocks critical actions",
  },
  {
    blocksV096Acceptance: false,
    category: "P0_SAFETY",
    evidence: "Export services reject forbidden classifications and hidden projection fields.",
    gateId: "WP15-G13-EXPORT-REDACTION",
    nonClaim: "Export is not raw data dump or internal-payload delivery.",
    ownerWp: "WP10/WP15",
    proofFiles: ["tests/export-safety.spec.ts", "tests/file-export-realism.spec.ts"],
    status: "COVERED",
    title: "Export redaction and forbidden payload exclusion",
  },
  {
    blocksV096Acceptance: false,
    category: "P0_SAFETY",
    evidence: "Preview, approval, generation, download, share and client acceptance remain separate states.",
    gateId: "WP15-G14-EXPORT-LIFECYCLE-SEPARATION",
    nonClaim: "Export approval is not download/share/client acceptance.",
    ownerWp: "WP10/WP14/WP15",
    proofFiles: ["tests/phase8-export-workflow-api.spec.ts", "tests/true-ux-export-scope-redaction-approval.spec.ts"],
    status: "COVERED",
    title: "Export lifecycle separation",
  },
  {
    blocksV096Acceptance: false,
    category: "P0_SAFETY",
    evidence: "Admin and security roles can govern access but cannot force release, sufficiency, visibility or export.",
    gateId: "WP15-G15-ADMIN-NON-BYPASS",
    nonClaim: "Admin is not superuser release authority.",
    ownerWp: "WP09/WP15",
    proofFiles: ["tests/governance-non-bypass.spec.ts", "tests/true-ux-governance-non-bypass.spec.ts"],
    status: "COVERED",
    title: "Admin/governance non-bypass",
  },
  {
    blocksV096Acceptance: false,
    category: "P0_SAFETY",
    evidence: "Invalid API requests return safe envelopes with no mutation, release, advice execution or hidden row disclosure.",
    gateId: "WP15-G16-API-ERROR-SAFETY",
    nonClaim: "API route existence is not acceptance proof.",
    ownerWp: "WP13/WP15",
    proofFiles: ["tests/p0-api-contract.spec.ts", "tests/fail-closed-error-envelope.spec.ts"],
    status: "COVERED",
    title: "API validation and safe error behavior",
  },
  {
    blocksV096Acceptance: false,
    category: "TRUE_UX",
    evidence: "Navigation groups order the core client work and keep reference/P1/HOLD routes out of productive nav.",
    gateId: "WP15-G17-JOURNEY-FIRST-IA",
    nonClaim: "Client-work navigation does not promote held routes.",
    ownerWp: "WP01/WP15",
    proofFiles: ["tests/navigation-shell.spec.ts"],
    status: "COVERED",
    title: "Client-work IA",
  },
  {
    blocksV096Acceptance: false,
    category: "TRUE_UX",
    evidence: "Page headers and product guidance expose job, gate, next step and blocker context.",
    gateId: "WP15-G18-PAGE-JOB-HEADER",
    nonClaim: "Header copy is guidance, not gate completion.",
    ownerWp: "WP01/WP12/WP15",
    proofFiles: ["tests/product-guidance-shell.spec.ts", "tests/route-smoke.spec.ts"],
    status: "COVERED",
    title: "Focus and header guidance",
  },
  {
    blocksV096Acceptance: false,
    category: "TRUE_UX",
    evidence: "Density tests use semantic page type and D1-D4 contracts instead of pixel assertions.",
    gateId: "WP15-G19-DENSITY-CONTRACT",
    nonClaim: "No pixel-perfect or screenshot acceptance is claimed.",
    ownerWp: "WP02/WP15",
    proofFiles: ["tests/true-ux-density.spec.ts"],
    status: "COVERED",
    title: "Density and page-type contract",
  },
  {
    blocksV096Acceptance: false,
    category: "TRUE_UX",
    evidence: "CTA tests assert one primary CTA, blocked reasons and recovery states on touched surfaces.",
    gateId: "WP15-G20-ONE-PRIMARY-CTA",
    nonClaim: "Disabled CTA presence is not action permission.",
    ownerWp: "WP11/WP12/WP15",
    proofFiles: ["tests/true-ux-cta-state.spec.ts", "tests/ui-state-boundaries.spec.ts"],
    status: "COVERED",
    title: "One primary CTA and state feedback",
  },
  {
    blocksV096Acceptance: false,
    category: "TRUE_UX",
    evidence: "Modal, drawer, guarded action, table and confirmation lifecycle tests cover open/close/cancel/block paths.",
    gateId: "WP15-G21-PRIMITIVE-LIFECYCLE",
    nonClaim: "Visual-only primitives are not accepted as interaction proof.",
    ownerWp: "WP11/WP15",
    proofFiles: ["tests/interaction-lifecycle.spec.ts", "tests/confirmation-lifecycle.spec.ts", "tests/true-ux-shared-primitives.spec.ts"],
    status: "COVERED",
    title: "Shared primitive lifecycle",
  },
  {
    blocksV096Acceptance: false,
    category: "TRUE_UX",
    evidence: "A11y tests cover keyboard, focus return, live status and accessible names on touched primitives and routes.",
    gateId: "WP15-G22-A11Y-FOCUS-STATUS",
    nonClaim: "This is targeted V0.96 a11y proof, not full WCAG certification.",
    ownerWp: "WP11/WP15",
    proofFiles: ["tests/true-ux-a11y.spec.ts", "tests/disabled-control-a11y-messaging.spec.ts"],
    status: "COVERED",
    title: "A11y focus, keyboard and status basics",
  },
  {
    blocksV096Acceptance: false,
    category: "TRUE_UX",
    evidence: "No-overclaim copy tests cover upload, evidence, AI draft, advisor, compliance, client, audit, admin and export boundaries.",
    gateId: "WP15-G23-NO-OVERCLAIM-COPY",
    nonClaim: "Copy names completed actions only, not downstream gates.",
    ownerWp: "WP12/WP15",
    proofFiles: ["tests/true-ux-no-overclaim-copy.spec.ts", "tests/ui-state-boundaries.spec.ts"],
    status: "COVERED",
    title: "No-overclaim microcopy",
  },
  {
    blocksV096Acceptance: false,
    category: "TRUE_UX",
    evidence: "Status/workflow badges declare visual-summary metadata and are not treated as completion gates.",
    gateId: "WP15-G24-STATUS-CHIP-NOT-GATE-PROOF",
    nonClaim: "Status chip or visual row alone is never proof.",
    ownerWp: "WP12/WP15",
    proofFiles: ["tests/true-ux-no-overclaim-copy.spec.ts", "tests/status-badge-affordance-pruning.spec.ts"],
    status: "COVERED",
    title: "Status chips are not completion gates",
  },
  {
    blocksV096Acceptance: false,
    category: "SCOPE_CONTROL",
    evidence: "Route registry and navigation tests keep P1/HOLD/reference routes registered-only or guarded.",
    gateId: "WP15-G25-P1-HOLD-NOT-ELEVATED",
    nonClaim: "Held committee, KYC/IPS, monitoring and reference routes are not accepted as implemented product journeys.",
    ownerWp: "WP00/WP15",
    proofFiles: ["tests/p0-acceptance.spec.ts", "tests/p1-hold-defensive-noninteractive.spec.ts", "tests/navigation-shell.spec.ts"],
    status: "COVERED",
    title: "P1/HOLD/reference routes not elevated",
  },
  {
    blocksV096Acceptance: false,
    category: "PROOF_ORCHESTRATION",
    evidence: "Canonical journey proof and P0 acceptance tests map evidence, analyst, advisor, compliance, client, audit and export slices.",
    gateId: "WP15-G26-POSITIVE-JOURNEY-SPINE",
    nonClaim: "This proves V0.96 demo-data acceptance, not full GA production readiness.",
    ownerWp: "WP15",
    proofFiles: ["tests/e2e/e2e-journey-proof-ws00-ws05.spec.ts", "tests/p0-acceptance.spec.ts"],
    status: "COVERED",
    title: "Positive V0.96 journey spine",
  },
  {
    blocksV096Acceptance: false,
    category: "PROOF_ORCHESTRATION",
    evidence: "This matrix and report provide the WP16 handoff index for commands, gates, proofs, non-claims and residual boundaries.",
    gateId: "WP15-G27-WP15-EVIDENCE-HANDOFF",
    nonClaim: "The evidence handoff does not override the True-UX handoff.",
    ownerWp: "WP15/WP16",
    proofFiles: [
      "tests/v0-96-p0-true-ux-acceptance.spec.ts",
      "ALPHAVEST_V0_96_P0_TRUE_UX_ACCEPTANCE_EVIDENCE.md",
      "V0_96_WP15_P0_TRUE_UX_ACCEPTANCE_SUITE_REPORT.md",
    ],
    status: "COVERED",
    title: "WP15 evidence handoff for WP16",
  },
];

export const wp15ExpectedBlockedOutOfScope = [
  {
    blockingOwner: "Route evolution / product decision",
    gateId: "WP15-B01-EXTERNAL-ADVISOR-GUEST-FULL-WORKFLOW",
    reason: "External advisor guest workflow remains conditional/P1 and must not be unlocked by acceptance tests.",
  },
  {
    blockingOwner: "Route evolution / safety decision",
    gateId: "WP15-B02-KYC-IPS-COMMITTEE-HELD-ROUTES",
    reason: "KYC, IPS, high-risk committee and selected monitoring routes remain HOLD/P1 guarded.",
  },
] as const;

export const wp15ValidationCommandSet = [
  "pnpm typecheck",
  "PLAYWRIGHT_PORT=3078 pnpm playwright test tests/v0-96-p0-true-ux-acceptance.spec.ts --workers=1",
  "PLAYWRIGHT_PORT=3079 pnpm playwright test tests/p0-acceptance.spec.ts tests/true-ux-p0-safety.spec.ts --workers=1",
  "PLAYWRIGHT_PORT=3080 pnpm playwright test tests/navigation-shell.spec.ts tests/true-ux-cta-state.spec.ts tests/true-ux-density.spec.ts --workers=1",
  "PLAYWRIGHT_PORT=3081 pnpm playwright test tests/true-ux-a11y.spec.ts tests/interaction-lifecycle.spec.ts tests/confirmation-lifecycle.spec.ts --workers=1",
  "PLAYWRIGHT_PORT=3082 pnpm playwright test tests/governance-non-bypass.spec.ts tests/export-safety.spec.ts tests/audit-fail-closed.spec.ts --workers=1",
  "PLAYWRIGHT_PORT=3083 pnpm playwright test tests/p0-api-contract.spec.ts tests/true-ux-client-projection.spec.ts tests/true-ux-api-service-ui-truth.spec.ts --workers=1",
  "PLAYWRIGHT_PORT=3084 pnpm playwright test tests/v0-96-ux-ia-delta-register.spec.ts --workers=1",
  "pnpm db:validate",
  "git diff --check",
  "mkdir -p test-results && pnpm lint",
] as const;

export function wp15CoverageSummary(entries = wp15CoverageMatrix) {
  return entries.reduce<Record<Wp15CoverageStatus, number>>(
    (summary, entry) => {
      summary[entry.status] += 1;
      return summary;
    },
    {
      BLOCKED: 0,
      CONFLICTING: 0,
      COVERED: 0,
      MISSING: 0,
      PARTIAL: 0,
    },
  );
}

export function wp15UnresolvedReleaseBlockers(entries = wp15CoverageMatrix) {
  return entries.filter((entry) => {
    if (entry.status === "MISSING" || entry.status === "CONFLICTING") return true;

    return entry.blocksV096Acceptance && (entry.status === "BLOCKED" || entry.status === "PARTIAL");
  });
}
